"""The wire the authoring client is written against.

The same arrangement `test_web_wire.py` makes for playing, for the same
reason. The client's own tests replay recorded frames rather than standing up
a Python service, and the risk in that is drift — a form that keeps passing
against a recording of a wizard that has since grown a field type. So the
recording is generated here, from a real project, and this test fails the
moment the two disagree. Regenerate it with:

    MACE_UPDATE_FIXTURES=1 pytest tests/test_web_author_wire.py

and read the diff before committing: a change here is a change to the wizard's
own screens, which both front-ends are written against.

It records `packs/games/peasants-quest` rather than a fixture pack on purpose.
A recording made from a two-location toy would never contain a picker with
anything interesting in it, and "the options arrive resolved" is the whole
claim the client rests on.
"""

import json
import os
import shutil
from pathlib import Path
from typing import Any

import pytest

from mace.wizard.studio import Studio, frame

#: Where the client's tests read it from.
FIXTURE = Path(__file__).resolve().parents[1] / "web" / "src" / "test" / "author.json"

#: The pack the recording is made from, and where its dependencies live.
PACKS = Path(__file__).resolve().parents[1] / "packs"
GAME = PACKS / "games" / "peasants-quest"


def recorded(root: Path) -> dict[str, Any]:
    """Open a copy of the game and write down every screen a client asks for.

    A copy rather than the pack itself, because the script answers a question
    and the whole point of the studio is that answering a question edits a
    file.

    Parameters
    ----------
    root : Path
        A scratch directory to copy the pack into.

    Returns
    -------
    dict
        The fixture, exactly as the service would have sent it.
    """
    working = root / "peasants-quest"
    shutil.copytree(GAME, working)
    studio = Studio.open(working, PACKS)

    return {
        "note": (
            "Generated by tests/test_web_author_wire.py from "
            "packs/games/peasants-quest. Do not edit by hand."
        ),
        "desk": frame(studio),
        "sections": {
            one: frame(studio, studio.section(one))
            for one in ("world", "scenes", "characters")
        },
        "manifest": frame(studio, studio.object("game")),
        "object": frame(studio, studio.object("locations", "fenmoor")),
        # A scene and a character, because between them they are the only
        # place the four *interactive* fields appear: conditions, effects, a
        # repeat, and a statblock. A recording without them would let the
        # cascade be written against JSON somebody imagined.
        "scene": frame(studio, studio.object("scenes", "talk-to-gorm")),
        "actor": frame(studio, studio.object("entities", "gorm")),
        # After an answer: the step that changed, and a desk that has moved
        # with it. A client that only refreshed the header when asked would
        # pass against a recording that did not include this.
        "answered": frame(
            studio,
            studio.answer("locations", "location.safe", True, "fenmoor"),
        ),
        "made": _made(studio),
        # The world map, which is the one screen a browser draws that a
        # terminal cannot.
        "atlas": studio.atlas(),
        # A sample rather than all thirty-odd recipes. The vocabulary's
        # shape is guarded by `test_wizard_studio.py`; what belongs in a
        # *client* fixture is what the client replays, and the browser does
        # not draw the cascade yet. Widen this when it does.
        "vocabulary": _sample(studio),
        "built": studio.build(
            "conditions", "hasItem", {"item": "fantasy.core:gold", "qty": 10}
        ),
    }


def _sample(studio: Studio) -> dict[str, Any]:
    """One recipe from each vocabulary, with this pack's options on it.

    Parameters
    ----------
    studio : Studio
        The open pack.

    Returns
    -------
    dict
        `conditions` and `effects`, one each.
    """
    whole = studio.vocabulary()
    return {
        kind: [one for one in whole[kind] if one["tag"] == tag]
        for kind, tag in (("conditions", "hasItem"), ("effects", "giveItem"))
    }


def _made(studio: Studio) -> dict[str, Any]:
    """Make a place, and record the screen it opens on.

    Parameters
    ----------
    studio : Studio
        The open pack.

    Returns
    -------
    dict
        The frame.
    """
    made = studio.create("locations", "The Long Moor", section="world")
    return frame(studio, studio.object("locations", made))


@pytest.fixture
def now(tmp_path: Path) -> dict[str, Any]:
    return recorded(tmp_path)


def test_the_recorded_wire_is_the_wire_the_wizard_speaks(
    now: dict[str, Any],
) -> None:
    """The client replays this; if it has moved, the client is wrong now."""
    if os.environ.get("MACE_UPDATE_FIXTURES"):
        FIXTURE.parent.mkdir(parents=True, exist_ok=True)
        FIXTURE.write_text(json.dumps(now, indent=2) + "\n", encoding="utf-8")
        pytest.skip("fixture regenerated")

    assert FIXTURE.exists(), (
        f"{FIXTURE} is missing. Generate it with "
        "MACE_UPDATE_FIXTURES=1 pytest tests/test_web_author_wire.py"
    )
    assert json.loads(FIXTURE.read_text(encoding="utf-8")) == now, (
        "the authoring client's recorded frames no longer match what the "
        "wizard sends. If that is intended, regenerate with "
        "MACE_UPDATE_FIXTURES=1 and say so in the commit message."
    )


def test_the_recording_has_a_picker_with_something_in_it(
    now: dict[str, Any],
) -> None:
    """Resolved options are the claim the whole client rests on."""
    steps = now["object"]["screen"]["steps"]
    entities = next(one for one in steps if one["id"] == "location.entities")
    assert len(entities["field"]["options"]) > 3
    assert all("label" in one for one in entities["field"]["options"])


def test_the_recording_covers_every_field_kind_the_client_draws(
    now: dict[str, Any],
) -> None:
    """A renderer written against a recording of half the kinds is half done."""
    kinds = {
        one["field"]["kind"]
        for screen in ("manifest", "object", "scene", "actor")
        for one in now[screen]["screen"]["steps"]
    }
    assert {
        "text",
        "text-list",
        "number",
        "select",
        "multi-select",
        "bool",
        "conditions",
        "effects",
        "repeat",
        "stat-allocator",
        "map-position",
    } <= kinds


def test_a_built_condition_arrives_already_in_english(now: dict[str, Any]) -> None:
    """A browser has no model and no naming service, so it must not decide."""
    steps = now["scene"]["screen"]["steps"]
    when = next(one for one in steps if one["id"] == "scene.when")
    assert when["entries"]
    assert all(one["said"] for one in when["entries"])
    assert all("authored" in one for one in when["entries"])


def test_a_repeat_arrives_as_entries_somebody_can_take_apart(
    now: dict[str, Any],
) -> None:
    steps = now["object"]["screen"]["steps"]
    exits = next(one for one in steps if one["id"] == "location.exits")
    assert len(exits["entries"]) == 2
    assert all(one["summary"] for one in exits["entries"])
    assert exits["field"]["steps"], "a repeat has to carry the flow for one entry"


def test_a_statblock_arrives_as_named_numbers(now: dict[str, Any]) -> None:
    steps = now["actor"]["screen"]["steps"]
    stats = next(one for one in steps if one["id"] == "entity.stats")
    assert any(one["stat"] == "strength" for one in stats["entries"])


def test_an_answer_moves_the_desk_in_the_same_reply(now: dict[str, Any]) -> None:
    assert now["answered"]["dirty"] == ["locations.yml"]
    assert now["answered"]["desk"]["tasks"]


def test_the_atlas_is_a_map_with_something_on_it(now: dict[str, Any]) -> None:
    """A map editor written against an empty map is a map editor untested."""
    drawn = now["atlas"]
    assert len(drawn["places"]) >= 3
    assert len(drawn["roads"]) >= 2
    assert any(one["x"] is not None for one in drawn["places"])
    assert all(one["exits"] is not None for one in drawn["places"])


def test_a_new_object_opens_unfinished(now: dict[str, Any]) -> None:
    made = now["made"]["screen"]
    assert made["id"] == "the-long-moor"
    assert any(not one["answered"] for one in made["steps"])


def test_the_recording_never_carries_the_authors_own_yaml_objects(
    now: dict[str, Any],
) -> None:
    """Comments and key order must not go over a wire."""
    json.dumps(now)  # would raise on anything JSON cannot encode
