"""The wire the web client is written against.

The client has its own tests, and they replay recorded frames rather than
standing up a Python service — a browser test that boots an engine is a slow
test that fails for reasons that are not about the browser.

The risk in that is drift: the client keeps passing against a recording of a
protocol the engine no longer speaks. So the recording is generated *here*,
from a real playthrough, and this test fails the moment the two disagree.
Regenerate it with:

    MACE_UPDATE_FIXTURES=1 pytest tests/test_web_wire.py

and read the diff before committing it — a change here is a change to the
contract every front-end is written against.
"""

import json
import os
from pathlib import Path
from typing import Any

import pytest

from mace.api.app import frame
from mace.content import load_library
from mace.engine.actions import decode
from mace.engine.creation import Character
from mace.session import Session

#: Where the client's tests read it from.
FIXTURE = Path(__file__).resolve().parents[1] / "web" / "src" / "test" / "frames.json"

#: The playthrough that gets recorded. Chosen to reach a fight: opening prose,
#: a menu, a journey with legs, an interruption, and a troll.
SCRIPT: tuple[dict[str, Any], ...] = (
    {"kind": "choose", "prompt": "Take the north road"},
    {"kind": "choose", "prompt": "Speak to the troll"},
    {"kind": "choose", "prompt": "Refuse, and put a hand on your hook"},
)


def recorded() -> dict[str, Any]:
    """Play the script and write down every frame it produced.

    Returns
    -------
    dict
        The fixture, exactly as the service would have sent it.
    """
    library = load_library(Path("packs"))
    session = Session.begin(
        library,
        "peasants-quest",
        seed="mace",
        combat_mode="tactical",
        character=Character(background="peasants-quest:farmhand", spend={}),
    )

    steps = []
    for action in SCRIPT:
        session.perform(decode(dict(action), offered=session.offered))
        steps.append({"action": action, "frame": frame("fixture", session)})

    return {
        "note": (
            "Generated by tests/test_web_wire.py from packs/games/peasants-quest. "
            "Do not edit by hand."
        ),
        "opening": _opening(library),
        "steps": steps,
    }


def _opening(library: Any) -> dict[str, Any]:
    """The frame a session opens on.

    Parameters
    ----------
    library : Library
        The loaded content.

    Returns
    -------
    dict
        The opening frame.
    """
    session = Session.begin(
        library,
        "peasants-quest",
        seed="mace",
        combat_mode="tactical",
        character=Character(background="peasants-quest:farmhand", spend={}),
    )
    return frame("fixture", session)


def test_the_recorded_wire_is_the_wire_the_engine_speaks() -> None:
    """The client replays this; if it has moved, the client is wrong now."""
    now = recorded()

    if os.environ.get("MACE_UPDATE_FIXTURES"):
        FIXTURE.parent.mkdir(parents=True, exist_ok=True)
        FIXTURE.write_text(json.dumps(now, indent=2) + "\n", encoding="utf-8")
        pytest.skip("fixture regenerated")

    assert FIXTURE.exists(), (
        f"{FIXTURE} is missing. Generate it with "
        "MACE_UPDATE_FIXTURES=1 pytest tests/test_web_wire.py"
    )
    assert json.loads(FIXTURE.read_text(encoding="utf-8")) == now, (
        "the web client's recorded frames no longer match what the engine "
        "sends. If that is intended, regenerate with MACE_UPDATE_FIXTURES=1 "
        "and say so in the commit message — it is a change to the contract "
        "every front-end is written against."
    )


def test_the_recording_reaches_a_fight() -> None:
    """It is a fixture for a combat view as well as a narrative one."""
    kinds = {
        event["kind"]
        for step in recorded()["steps"]
        for event in step["frame"]["events"]
    }
    assert {"narrate", "choices", "travel.leg", "combat.tell"} <= kinds
