/**
 * The recorded authoring wire, and a fake wizard that speaks it.
 *
 * `author.json` is generated by `tests/test_web_author_wire.py` from a real
 * copy of `packs/games/peasants-quest`, and a Python test fails the moment the
 * wizard stops sending what is recorded here. Same arrangement as `wire.ts`,
 * same reason: a client test that invents its own JSON passes forever,
 * including after the projection moves underneath it.
 */

import recording from "./author.json";
import type { Built, Frame, Vocabulary } from "../author/protocol";

interface Recording {
  desk: Frame;
  section: Frame;
  manifest: Frame;
  object: Frame;
  answered: Frame;
  made: Frame;
  vocabulary: Vocabulary;
  built: Built;
}

const wire = recording as unknown as Recording;

export const desk = wire.desk;
export const section = wire.section;
export const manifest = wire.manifest;
export const object = wire.object;
export const answered = wire.answered;
export const made = wire.made;
export const vocabulary = wire.vocabulary;
export const built = wire.built;

/** What a request was made of the fake wizard. */
export interface Call {
  path: string;
  method: string;
  body: unknown;
}

/**
 * Stand up a wizard that answers the way the real one does.
 *
 * Routes rather than a script, because authoring has no order to it: the
 * whole design of the task list is that an author visits things in whatever
 * order they like.
 */
export function fakeStudio(options: { refuse?: string; absent?: boolean } = {}) {
  const calls: Call[] = [];

  const fetcher = async (
    input: RequestInfo | URL,
    init?: RequestInit,
  ): Promise<Response> => {
    const path = String(input);
    const method = init?.method ?? "GET";
    const body = init?.body === undefined ? null : JSON.parse(String(init.body));
    calls.push({ path, method, body });

    const reply = (payload: unknown, status = 200) =>
      new Response(JSON.stringify(payload), {
        status,
        headers: { "content-type": "application/json" },
      });

    // Nothing ran `mace author --web`: every authoring path is a 404 from
    // whatever is serving the files.
    if (options.absent === true) return reply({ detail: "not found" }, 404);

    if (path.endsWith("/api/author")) return reply(desk);
    if (path.endsWith("/vocabulary")) return reply(vocabulary);
    if (path.includes("/sections/")) return reply(section);
    if (path.endsWith("/build")) return reply(built);
    if (path.endsWith("/save")) {
      return reply({ ...desk, dirty: [], screen: { saved: ["locations.yml"] } });
    }
    if (path.endsWith("/answers")) {
      if (options.refuse !== undefined) {
        return reply({ detail: options.refuse }, 400);
      }
      return reply(answered);
    }
    if (path.includes("/objects/")) {
      if (method === "POST") {
        if (options.refuse !== undefined) {
          return reply({ detail: options.refuse }, 400);
        }
        return reply(made, 201);
      }
      if (method === "DELETE") return reply(section);
      if (path.endsWith("/objects/game")) return reply(manifest);
      return reply(object);
    }
    return reply({ detail: `no route for ${path}` }, 404);
  };

  return { calls, fetcher };
}
