/**
 * The recorded wire, and a fake service that speaks it.
 *
 * `frames.json` is generated by `tests/test_web_wire.py` from a real
 * playthrough of `packs/games/peasants-quest`, and a Python test fails the
 * moment the engine stops sending what is recorded here. That is the whole
 * point of recording it: a client test that invents its own JSON passes
 * forever, including after the protocol moves underneath it.
 */

import recording from "./frames.json";
import type { CreationOffer, Frame, GameSummary } from "../protocol";

interface Recording {
  opening: Frame;
  steps: Array<{ action: Record<string, unknown>; frame: Frame }>;
  /** The same road fought on the clock, in `reflex` mode. */
  fight: Array<{ action: Record<string, unknown>; frame: Frame }>;
  /** Which key the *terminal* binds to each answer in that fight. */
  keys: Record<string, string>;
}

const wire = recording as unknown as Recording;

export const opening: Frame = wire.opening;
export const steps = wire.steps;
export const fight = wire.fight;
export const terminalKeys = wire.keys;

/** The frame the nth action of the recorded fight produced. */
export function afterFight(index: number): Frame {
  const step = fight[index];
  if (step === undefined) throw new Error(`no recorded fight step ${index}`);
  return step.frame;
}

/** The frame the nth scripted action produced. */
export function afterStep(index: number): Frame {
  const step = steps[index];
  if (step === undefined) throw new Error(`no recorded step ${index}`);
  return step.frame;
}

export const GAMES: GameSummary[] = [
  {
    id: "peasants-quest",
    name: "A Peasant's Quest",
    version: "0.1.0",
    description: "Seven days to reach Hagan's Castle.",
  },
];

export const CREATION: CreationOffer = {
  asksAnything: true,
  points: 15,
  backgrounds: [
    {
      id: "peasants-quest:farmhand",
      name: "Farmhand",
      description: "Twenty-five years of barley.",
      grants: ["strength +8", "endurance +6", "2 × bread"],
    },
    {
      id: "peasants-quest:poacher",
      name: "Poacher",
      description: "You know the wood.",
      grants: ["stealth +15", "speed +5"],
    },
  ],
  stats: [
    { stat: "strength", base: 40, minimum: 0, maximum: 100, room: 60 },
    { stat: "speed", base: 41, minimum: 0, maximum: 100, room: 59 },
  ],
};

/** What a request was made of the fake service. */
export interface Call {
  path: string;
  method: string;
  body: unknown;
}

/**
 * Stand up a service that answers the way the real one does.
 *
 * Actions walk the recording in order, so a test that clicks three times sees
 * the three frames the engine actually produced for those three actions.
 */
export function fakeService(
  options: { failOpen?: string; script?: typeof steps } = {},
) {
  const calls: Call[] = [];
  const script = options.script ?? steps;
  let step = 0;

  const fetcher = async (
    input: RequestInfo | URL,
    init?: RequestInit,
  ): Promise<Response> => {
    const path = String(input);
    const method = init?.method ?? "GET";
    const body = init?.body === undefined ? null : JSON.parse(String(init.body));
    calls.push({ path, method, body });

    const reply = (payload: unknown, status = 200) =>
      new Response(JSON.stringify(payload), {
        status,
        headers: { "content-type": "application/json" },
      });

    if (path === "/api/games") return reply({ games: GAMES });
    if (path.includes("/creation")) return reply(CREATION);
    if (path === "/api/sessions" && method === "POST") {
      if (options.failOpen !== undefined) {
        return reply({ detail: options.failOpen }, 400);
      }
      return reply(opening, 201);
    }
    if (path.endsWith("/save")) {
      return reply({
        format: 1,
        pack: "peasants-quest",
        seed: "mace",
        packs: {},
        actions: script.slice(0, step).map((one) => one.action),
      });
    }
    if (path.endsWith("/actions")) {
      const frame = script[step]?.frame;
      step += 1;
      if (frame === undefined) return reply({ detail: "nothing recorded" }, 400);
      return reply(frame);
    }
    return reply({ detail: `no route for ${path}` }, 404);
  };

  return { calls, fetcher, taken: () => step };
}

/**
 * A WebSocket that never connects.
 *
 * The client is meant to notice and fall back to `POST`, which is the
 * behaviour worth testing: a player whose socket died should keep playing.
 */
export class DeadSocket {
  static readonly OPEN = 1;
  readyState = 3;
  onopen: (() => void) | null = null;
  onmessage: ((event: MessageEvent<string>) => void) | null = null;
  onerror: (() => void) | null = null;
  onclose: (() => void) | null = null;

  constructor(readonly url: string) {
    queueMicrotask(() => this.onclose?.());
  }

  send(): void {
    throw new Error("this socket is not open");
  }

  close(): void {}
}

/**
 * A WebSocket that behaves the way the service's does.
 *
 * Greets with the current frame — which the client is expected to swallow,
 * having already rendered it from the `POST` that opened the session — then
 * answers each action with the next recorded frame.
 */
export class LiveSocket {
  static readonly OPEN = 1;
  static last: LiveSocket | null = null;

  readyState = 0;
  sent: unknown[] = [];
  onopen: (() => void) | null = null;
  onmessage: ((event: MessageEvent<string>) => void) | null = null;
  onerror: (() => void) | null = null;
  onclose: (() => void) | null = null;

  private step = 0;

  constructor(readonly url: string) {
    LiveSocket.last = this;
    queueMicrotask(() => {
      this.readyState = LiveSocket.OPEN;
      this.onopen?.();
      this.deliver(opening);
    });
  }

  send(payload: string): void {
    this.sent.push(JSON.parse(payload));
    const next = steps[this.step]?.frame;
    this.step += 1;
    queueMicrotask(() =>
      this.deliver(next ?? ({ error: "nothing recorded" } as unknown as Frame)),
    );
  }

  close(): void {
    this.readyState = 3;
  }

  private deliver(body: Frame): void {
    this.onmessage?.(new MessageEvent("message", { data: JSON.stringify(body) }));
  }
}
