routes:
  - id: scorg-s-trail
    name: Scorg's Trail
    from: scorg-s-cave
    to: the-black-forest
    ticks: 1
    terrain: fantasy.core:mountain-path
    dangerLevel: 8
    legDescriptions:
      - A winding beaten trail between the dreaded Black Forest and the cave.
    bidirectional: true
  - id: the-trail-of-dread
    name: The Trail of Dread
    from: fairvale
    to: the-black-forest
    ticks: 5
    terrain: fantasy.core:mountain-path
    dangerLevel: 7
    legDescriptions:
      - The difficult walk-way at the bottom of the crevasse with perches and caverns above makes you feel vulnerable and defenseless.
    bidirectional: true
